name = "id1"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true
[[routes]]
pattern = "id1.yasnaya.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.id1.yasnaya.my.id"
custom_domain = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "00f7b9a7-71d7-4999-820b-914248a601a4"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
